### ISSUE TITLE
SSL Setup

### ISSUE THREAD

**Issue by Atrophius** [OrlandoDevs/orlandodevs.github.io#14]
We're currently considering adding SSL termination through CloudFlare. Here's the details: https://www.cloudflare.com/plans/

Here's the requirements:
- [x] Need domain transfer(s) to be completed
- [x] Create CloudFlare account
- [x] Point CloudFlare account at github.io domain
- [x] Point DNS for domains at CloudFlare
- [x] Need cache busting API call implemented (probably through a Github web hook pushing into a separate service -- we were thinking possibly AWS Lambda or some other similar mini node service)

**Comment by sergiocruz** [comment]
I just created a CloudFlare account, under our community's email address and password.

**Comment by sergiocruz** [comment]
Ended up using AWS Lambda to get this done... @Atrophius and I setup a webhook to clear the cache every time the pages are built.

The Lambda will have to be updated when we finally own the domain name, since there are a few settings that need to be in place.

**Comment by sergiocruz** [comment]
@Atrophius I think we're good to close this one, since we finalized this yesterday :D

**Comment by Atrophius** [comment]
Boom. Resolved.
