### ISSUE TITLE
Updating board and advisors list.

### ISSUE THREAD

**Issue by germangamboa95** [OrlandoDevs/orlandodevs.github.io#50]
We still have the old members listed. May we update it to the new ones? I'll be more than happy to do the PR if I had the info on who is who.

**Comment by csndra0504** [comment]
Thanks @germangamboa95! I am currently working to gather that info. I figure we can update the list pretty easily for an immediate solution, but I intend to also find a designer to do a nice layout with headshots. Info & requirements are on the way! 

cc @davidkpiano

**Comment by csndra0504** [comment]
@germangamboa95 Sorry this took so long to get together!

## Updated content is here:
https://docs.google.com/document/d/1ma7jk9dBwU1ESU1QJTF2JZOBYANI8ogp4OLPK5YaA6E/edit#

## Needs to be updated here:
https://orlandodevs.com/about/

## Contributor guide: https://github.com/OrlandoDevs/orlandodevs.github.io/blob/master/CONTRIBUTING.md

Let me know if you need anything else! Thanks a bunch for your offer to help!!! 🙌
